const KIDS_DATA = [
  {
    "image":"assets/images/babykids18.jpg"
  },{
    "image":"assets/images/babykids1.jpg"
  },
  {
    "image":"assets/images/babykids2.jpg"
  },
  {
    "image":"assets/images/babykids4.jpg"
  },
  {
    "image":"assets/images/babykids5.jpg"
  },
  {
    "image":"assets/images/babykids6.jpg"
  },
  {
    "image":"assets/images/babykids7.jpg"
  },
  {
    "image":"assets/images/babykids8.jpg"
  },

  {
    "image":"assets/images/babykids9.jpg"
  },
  {
    "image":"assets/images/babykids3.jpg"
  },
  {
    "image":"assets/images/babykids10.jpg"
  },
  {
    "image":"assets/images/babykids11.jpg"
  },
  {
    "image":"assets/images/babykids12.jpg"
  },
  {
    "image":"assets/images/babykids13.jpg"
  },
  {
    "image":"assets/images/babykids14.jpg"
  },
  {
    "image":"assets/images/babykids15.jpg"
  },
  {
    "image":"assets/images/babykids16.jpg"
  },
  {
    "image":"assets/images/babykids17.jpg"
  }
];